# Generated by Django 5.0.1 on 2024-01-08 06:33

import datetime
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=100)),
                ('contractual', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=7, max_length=7, null=True)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 8, 6, 33, 8, 694619, tzinfo=datetime.timezone.utc))),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
