# Generated by Django 5.0.1 on 2024-01-08 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 6, 40, 25, 979362, tzinfo=datetime.timezone.utc)),
        ),
    ]
