# Generated by Django 5.0.1 on 2024-01-08 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 6, 41, 37, 655746, tzinfo=datetime.timezone.utc)),
        ),
    ]
