# Generated by Django 5.0.1 on 2024-01-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_added',
        ),
    ]
